services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: govdata # You can change the default database name here
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  chromadb-admin:
    image: fengzhichao/chromadb-admin:latest
    container_name: chromadb-admin
    ports:
      - "3001:3001"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  db_data: