services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: govdata # You can change the default database name here
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/chroma/chroma # Persists data in ./chroma_data relative to docker-compose.yaml
    ports:
      - "8082:8000"
    # Add any other necessary configurations like command or environment variables if needed.

volumes:
  db_data: