FEW_SHOT_EXAMPLES_FOR_DICT_OUTPUT_STR = """
Example 1:
Question: "Show me all customers from Germany who ordered iPhone 14 Pro"
Hint: "Focus on location, customer entity, and specific product mentions."
Output:
```json
{"keywords": ["customers", "location", "product"], "phrases": ["Germany", "iPhone 14 Pro"]}
```

Example 2:
Question: "List the top 5 employees by salary in the sales department"
Hint: "Consider job roles, compensation, and organizational units."
Output:
```json
{"keywords": ["employees", "salary", "department"], "phrases": ["sales"]}
```

Example 3:
Question: "Find orders placed in 2023 for user_id 123"
Hint: "Look for date constraints and user identifiers."
Output:
```json
{"keywords": ["orders", "user_id", "year"], "phrases": ["2023", "123"]}
```

Example 4:
Question: "What are the most common issues reported for the 'Alpha' project last quarter?"
Hint: "Identify the project name, timeframe, and the type of information requested (issues)."
Output:
```json
{"keywords": ["issues", "project", "quarter"], "phrases": ["Alpha"]}
```

Example 5:
Question: "Calculate total revenue generated by region for Q3 2024"
Hint: "Focus on metrics, geographical grouping, and time periods."
Output:
```json
{"keywords": ["revenue", "region", "total", "quarter"], "phrases": ["Q3", "2024"]}
```

Example 6:
Question: "Which products have inventory below 50 units in warehouse B?"
Hint: "Pay attention to thresholds, locations, and item quantities."
Output:
```json
{"keywords": ["products", "inventory", "units", "warehouse"], "phrases": ["50", "B"]}
```

Example 7:
Question: "Show me pending invoices for Microsoft exceeding $10,000"
Hint: "Look for status indicators, company names, and monetary thresholds."
Output:
```json
{"keywords": ["invoices", "status", "amount", "company"], "phrases": ["pending", "Microsoft", "10000"]}
```

Example 8:
Question: "Get all support tickets created by email domain @acme.com with priority high"
Hint: "Identify the data type, filtering criteria including patterns and severity levels."
Output:
```json
{"keywords": ["tickets", "support", "email", "domain", "priority"], "phrases": ["@acme.com", "high"]}
```

Example 9:
Question: "Average response time for API endpoint /auth/login during peak hours"
Hint: "Consider performance metrics, specific endpoints, and temporal patterns."
Output:
```json
{"keywords": ["response", "time", "average", "API", "endpoint"], "phrases": ["/auth/login"]}
```

Example 10:
Question: "List active subscriptions expiring in March 2025"
Hint: "Focus on status, lifecycle events, and date ranges."
Output:
```json
{"keywords": ["subscriptions", "status", "expiration", "date"], "phrases": ["active", "March 2025"]}
```

Example 11:
Question: "How many failed login attempts from IP address 192.168.1.100 today?"
Hint: "Look for event types, network identifiers, and time references."
Output:
```json
{"keywords": ["login", "attempts", "status", "IP", "address", "count"], "phrases": ["failed", "192.168.1.100"]}
```

Example 12:
Question: "Find transactions tagged as 'refund' processed by user admin_sarah"
Hint: "Identify transaction types, labels/tags, and user identifiers."
Output:
```json
{"keywords": ["transactions", "tags", "user"], "phrases": ["refund", "admin_sarah"]}
```

Example 13:
Question: "Show shipments to California with tracking status 'in transit' using FedEx"
Hint: "Focus on destination, delivery status, and carrier information."
Output:
```json
{"keywords": ["shipments", "destination", "tracking", "status", "carrier"], "phrases": ["California", "in transit", "FedEx"]}
```

Example 14:
Question: "Get all Toyota Camry vehicles sold in January with mileage under 30000"
Hint: "Consider vehicle make/model, time period, and condition metrics."
Output:
```json
{"keywords": ["vehicles", "make", "model", "mileage", "month"], "phrases": ["Toyota Camry", "January", "30000"]}
```

Example 15:
Question: "Which suppliers from Japan have contract value greater than 500000 yen?"
Hint: "Look at supplier location, contract metrics, and currency amounts."
Output:
```json
{"keywords": ["suppliers", "location", "contract", "value", "currency"], "phrases": ["Japan", "500000", "yen"]}
```

Example 16:
Question: "Show me all customers who made more than 5 purchases"
Hint: "Focus on customer entity and purchase frequency."
Output:
```json
{"keywords": ["customers", "purchases", "count"], "phrases": []}
```

Example 17:
Question: "Find employees with the highest performance rating"
Hint: "Consider employee attributes and ranking metrics."
Output:
```json
{"keywords": ["employees", "performance", "rating"], "phrases": []}
```

Example 18:
Question: "List products that need restocking soon"
Hint: "Focus on inventory levels and stock status."
Output:
```json
{"keywords": ["products", "inventory", "stock", "status"], "phrases": []}
```
"""

PROMPT = """
You are a linguistics expert specializing in information extraction for database queries.
Your task is to analyze the given question and hint to identify and extract keywords and keyphrases that map to database concepts (tables, columns, attributes) and specific column values.

## Instructions

1. **Read the Question Carefully**: Identify the primary focus and specific details. Look for:
   - Entity types that map to table names (customers, orders, employees, products)
   - Attribute names that map to column names (salary, status, location, date)
   - Specific values that could exist in database columns

2. **Analyze the Hint**: The hint directs attention toward relevant elements for answering the question. Extract terms that provide clarity about database structure or filtering criteria.

3. **Extract Keywords and Phrases**:
   - **Keywords**: Nouns and nominal phrases representing database concepts:
     - Entity types (e.g., "customers", "orders", "employees")
     - Attribute/column names (e.g., "salary", "status", "location", "date")
     - Measurement types (e.g., "count", "total", "average")
     - DO NOT include verbs or actions
   
   - **Phrases**: ONLY specific values that could exist as data in database columns:
     - Named entities (company names, product names, locations, person names)
     - Literal values (numbers, identifiers, codes, dates)
     - Status values (e.g., "pending", "active", "failed", "in transit")
     - Categorical values (e.g., "high", "sales", "refund")
     - DO NOT include comparative operators or descriptive phrases
     - If no concrete values exist in the question, leave phrases array EMPTY

4. **Combine Findings**: Merge extractions from both the question and hint into a single JSON object.

## Guidelines

- Keywords should be nouns that could match table/column names or descriptions in a database schema
- Phrases must ONLY contain actual values that could be stored in database columns
- Phrases should NOT include operators like "below", "exceeding", "greater than", "more than" - only the actual values
- Preserve original phrasing from the question for phrases
- Extract actual terms present—do not invent or paraphrase
- Avoid including verbs in keywords
- If the question has no specific values (like "highest", "most", "soon"), return empty phrases array

## Output Format

Return ONLY a JSON object with this structure:

```json
{{
  "keywords": ["entity1", "attribute1", ...],
  "phrases": ["value1", "value2", ...]
}}
```

No explanations, commentary, or additional text.

## EXAMPLES 
{FEWSHOT_EXAMPLES}

**************************
Given the following question and hint, identify and extract all relevant keywords and phrases.

** USER QUESTION **
{QUESTION}

** EVIDENCE **
{HINT}
"""